<!DOCTYPE html>
<html>
<head>
    <title>ONLINE SCHOOL</title>
</head>
<body>
<h1>ONLINE SCHOOL</h1><hr>
<h3>Курс по написанию оконных приложений на C#</h3>
<br>
<h3>Курс по написанию оконных приложений на C#</h3>
<div>
    <p><b>Николай С. | <a href="/front-tutor">Подробнее...</a></b></p>
    <p><b>Сергей Б. | <a href="/front-tutor">Подробнее...</a></b></p>
    <p><b>Александр М. | <a href="/front-tutor">Подробнее...</a></b></p>
    <p><b>Роксана З. | <a href="/front-tutor">Подробнее...</a></b></p>
</div>
<h3>Связаться с нами<a href="/front-tutor"> по почте </a></h3>
</body>
</html>