<!DOCTYPE html>
<html>
<head>
    <title>ONLINE SCHOOL</title>
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
<h1>ONLINE SCHOOL</h1><hr>
</nav>
<h3>Курс по написанию оконных приложений на C#</h3>
<br>
<h1>Куратор Николай С.</h1>

<h3>Разработчик с 2021 года</h3>
<h3>Живет и работает в Москве</h3>
<img alt="tutor" src="/images/img.png">
<h3>Связаться с Николаем<a href="/front-tutor"> по почте </a></h3>
<h3><a href="/front-tutor"> На главную страницу </a></h3>
<br>
<h3 style="accent-color: blue">Produced by student ITMO, Saint-Petersburg, 2024</h3>
</body>
</html>